# -*- coding: utf-8 -*-
"""
The code to generate the windows themselves.

These files were automatically generated by PyQt4 UI code generator 4.9.6.
DO NOT EDIT THESE FILES MANUALLY!
"""
__author__ = 'Sohhla'