# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../qt/qt_add.ui'
#
# Created: Wed Apr 08 23:48:02 2015
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(1033, 540)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/images/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setMargin(10)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setVerticalSpacing(4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupbox_anime_folder = QtGui.QGroupBox(Dialog)
        self.groupbox_anime_folder.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_anime_folder.sizePolicy().hasHeightForWidth())
        self.groupbox_anime_folder.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupbox_anime_folder.setFont(font)
        self.groupbox_anime_folder.setMouseTracking(True)
        self.groupbox_anime_folder.setStyleSheet(_fromUtf8("color: rgb(120, 120, 120);"))
        self.groupbox_anime_folder.setObjectName(_fromUtf8("groupbox_anime_folder"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupbox_anime_folder)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.radio_use_default_anime_folder = QtGui.QRadioButton(self.groupbox_anime_folder)
        self.radio_use_default_anime_folder.setEnabled(False)
        self.radio_use_default_anime_folder.setMaximumSize(QtCore.QSize(552, 16777215))
        self.radio_use_default_anime_folder.setChecked(True)
        self.radio_use_default_anime_folder.setObjectName(_fromUtf8("radio_use_default_anime_folder"))
        self.verticalLayout_2.addWidget(self.radio_use_default_anime_folder)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radio_use_another_anime_folder = QtGui.QRadioButton(self.groupbox_anime_folder)
        self.radio_use_another_anime_folder.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radio_use_another_anime_folder.sizePolicy().hasHeightForWidth())
        self.radio_use_another_anime_folder.setSizePolicy(sizePolicy)
        self.radio_use_another_anime_folder.setText(_fromUtf8(""))
        self.radio_use_another_anime_folder.setObjectName(_fromUtf8("radio_use_another_anime_folder"))
        self.horizontalLayout.addWidget(self.radio_use_another_anime_folder)
        self.text_anime_folder = QtGui.QLineEdit(self.groupbox_anime_folder)
        self.text_anime_folder.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_anime_folder.sizePolicy().hasHeightForWidth())
        self.text_anime_folder.setSizePolicy(sizePolicy)
        self.text_anime_folder.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.text_anime_folder.setText(_fromUtf8(""))
        self.text_anime_folder.setReadOnly(False)
        self.text_anime_folder.setObjectName(_fromUtf8("text_anime_folder"))
        self.horizontalLayout.addWidget(self.text_anime_folder)
        self.button_anime_folder = QtGui.QPushButton(self.groupbox_anime_folder)
        self.button_anime_folder.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_anime_folder.sizePolicy().hasHeightForWidth())
        self.button_anime_folder.setSizePolicy(sizePolicy)
        self.button_anime_folder.setMinimumSize(QtCore.QSize(45, 0))
        self.button_anime_folder.setMaximumSize(QtCore.QSize(45, 16777215))
        self.button_anime_folder.setMouseTracking(True)
        self.button_anime_folder.setStyleSheet(_fromUtf8("QPushButton {\n"
"     border: 1px solid #8f8f91;\n"
"     border-radius: 4px;\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"     padding-left: 4px;\n"
"     padding-right: 4px;\n"
" }\n"
"\n"
" QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }\n"
"\n"
" QPushButton:flat {\n"
"     border: none;\n"
" }"))
        self.button_anime_folder.setObjectName(_fromUtf8("button_anime_folder"))
        self.horizontalLayout.addWidget(self.button_anime_folder)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupbox_anime_folder, 3, 0, 1, 1)
        self.groupbox_search = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_search.sizePolicy().hasHeightForWidth())
        self.groupbox_search.setSizePolicy(sizePolicy)
        self.groupbox_search.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupbox_search.setFont(font)
        self.groupbox_search.setObjectName(_fromUtf8("groupbox_search"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupbox_search)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.horizontalLayout_3.setContentsMargins(8, 3, 8, 8)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setHorizontalSpacing(2)
        self.formLayout.setVerticalSpacing(5)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_name = QtGui.QLabel(self.groupbox_search)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_name.setFont(font)
        self.label_name.setMouseTracking(True)
        self.label_name.setObjectName(_fromUtf8("label_name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_name)
        self.label_search = QtGui.QLabel(self.groupbox_search)
        self.label_search.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_search.setFont(font)
        self.label_search.setMouseTracking(True)
        self.label_search.setObjectName(_fromUtf8("label_search"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_search)
        self.label_episode = QtGui.QLabel(self.groupbox_search)
        self.label_episode.setEnabled(False)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_episode.setFont(font)
        self.label_episode.setMouseTracking(True)
        self.label_episode.setObjectName(_fromUtf8("label_episode"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_episode)
        self.text_name = QtGui.QLineEdit(self.groupbox_search)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.text_name.setFont(font)
        self.text_name.setObjectName(_fromUtf8("text_name"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.text_name)
        self.text_search = QtGui.QTextEdit(self.groupbox_search)
        self.text_search.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_search.sizePolicy().hasHeightForWidth())
        self.text_search.setSizePolicy(sizePolicy)
        self.text_search.setMinimumSize(QtCore.QSize(300, 70))
        self.text_search.setMaximumSize(QtCore.QSize(16777215, 70))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.text_search.setFont(font)
        self.text_search.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.text_search.setMouseTracking(True)
        self.text_search.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.text_search.setTabChangesFocus(True)
        self.text_search.setAcceptRichText(False)
        self.text_search.setObjectName(_fromUtf8("text_search"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.text_search)
        self.text_episode = QtGui.QLineEdit(self.groupbox_search)
        self.text_episode.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_episode.sizePolicy().hasHeightForWidth())
        self.text_episode.setSizePolicy(sizePolicy)
        self.text_episode.setMinimumSize(QtCore.QSize(35, 0))
        self.text_episode.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.text_episode.setFont(font)
        self.text_episode.setMaxLength(3)
        self.text_episode.setObjectName(_fromUtf8("text_episode"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.text_episode)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.checkbox_anime_index = QtGui.QCheckBox(self.groupbox_search)
        self.checkbox_anime_index.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_anime_index.sizePolicy().hasHeightForWidth())
        self.checkbox_anime_index.setSizePolicy(sizePolicy)
        self.checkbox_anime_index.setMinimumSize(QtCore.QSize(0, 0))
        self.checkbox_anime_index.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_anime_index.setFont(font)
        self.checkbox_anime_index.setChecked(True)
        self.checkbox_anime_index.setObjectName(_fromUtf8("checkbox_anime_index"))
        self.verticalLayout.addWidget(self.checkbox_anime_index)
        self.checkbox_anime_tosho = QtGui.QCheckBox(self.groupbox_search)
        self.checkbox_anime_tosho.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_anime_tosho.sizePolicy().hasHeightForWidth())
        self.checkbox_anime_tosho.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_anime_tosho.setFont(font)
        self.checkbox_anime_tosho.setChecked(True)
        self.checkbox_anime_tosho.setObjectName(_fromUtf8("checkbox_anime_tosho"))
        self.verticalLayout.addWidget(self.checkbox_anime_tosho)
        self.checkbox_anirena = QtGui.QCheckBox(self.groupbox_search)
        self.checkbox_anirena.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_anirena.sizePolicy().hasHeightForWidth())
        self.checkbox_anirena.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_anirena.setFont(font)
        self.checkbox_anirena.setChecked(True)
        self.checkbox_anirena.setObjectName(_fromUtf8("checkbox_anirena"))
        self.verticalLayout.addWidget(self.checkbox_anirena)
        self.checkbox_nyaa = QtGui.QCheckBox(self.groupbox_search)
        self.checkbox_nyaa.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_nyaa.sizePolicy().hasHeightForWidth())
        self.checkbox_nyaa.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_nyaa.setFont(font)
        self.checkbox_nyaa.setChecked(True)
        self.checkbox_nyaa.setObjectName(_fromUtf8("checkbox_nyaa"))
        self.verticalLayout.addWidget(self.checkbox_nyaa)
        self.checkbox_tokyotosho = QtGui.QCheckBox(self.groupbox_search)
        self.checkbox_tokyotosho.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkbox_tokyotosho.sizePolicy().hasHeightForWidth())
        self.checkbox_tokyotosho.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.checkbox_tokyotosho.setFont(font)
        self.checkbox_tokyotosho.setChecked(True)
        self.checkbox_tokyotosho.setObjectName(_fromUtf8("checkbox_tokyotosho"))
        self.verticalLayout.addWidget(self.checkbox_tokyotosho)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.button_search = QtGui.QPushButton(self.groupbox_search)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_search.sizePolicy().hasHeightForWidth())
        self.button_search.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.button_search.setFont(font)
        self.button_search.setStyleSheet(_fromUtf8("QPushButton {\n"
"     border: 1px solid #8f8f91;\n"
"     border-radius: 4px;\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
"     padding-left: 4px;\n"
"     padding-right: 4px;\n"
" }\n"
"\n"
" QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }\n"
"\n"
" QPushButton:flat {\n"
"     border: none;\n"
" }"))
        self.button_search.setObjectName(_fromUtf8("button_search"))
        self.horizontalLayout_3.addWidget(self.button_search)
        self.gridLayout.addWidget(self.groupbox_search, 0, 0, 1, 1)
        self.groupbox_information = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupbox_information.sizePolicy().hasHeightForWidth())
        self.groupbox_information.setSizePolicy(sizePolicy)
        self.groupbox_information.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupbox_information.setFont(font)
        self.groupbox_information.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);"))
        self.groupbox_information.setObjectName(_fromUtf8("groupbox_information"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupbox_information)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setContentsMargins(8, 0, 8, 8)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.groupbox_information)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(390, 129))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 390, 129))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setMargin(3)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.label_information = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_information.sizePolicy().hasHeightForWidth())
        self.label_information.setSizePolicy(sizePolicy)
        self.label_information.setMinimumSize(QtCore.QSize(0, 0))
        self.label_information.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_information.setFont(font)
        self.label_information.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);"))
        self.label_information.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignTop)
        self.label_information.setWordWrap(True)
        self.label_information.setIndent(0)
        self.label_information.setOpenExternalLinks(True)
        self.label_information.setObjectName(_fromUtf8("label_information"))
        self.verticalLayout_11.addWidget(self.label_information)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.gridLayout.addWidget(self.groupbox_information, 0, 1, 1, 1)
        self.button_add = QtGui.QPushButton(Dialog)
        self.button_add.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_add.sizePolicy().hasHeightForWidth())
        self.button_add.setSizePolicy(sizePolicy)
        self.button_add.setStyleSheet(_fromUtf8("QPushButton {\n"
"     border: 1px solid #8f8f91;\n"
"     border-radius: 4px;\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #f6f7fa, stop: 1 #dadbde);\n"
" }\n"
"\n"
" QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }\n"
"\n"
" QPushButton:flat {\n"
"     border: none;\n"
" }"))
        self.button_add.setObjectName(_fromUtf8("button_add"))
        self.gridLayout.addWidget(self.button_add, 3, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_all = QtGui.QWidget()
        self.tab_all.setMouseTracking(True)
        self.tab_all.setObjectName(_fromUtf8("tab_all"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_all)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.text_results_all = QtGui.QTextBrowser(self.tab_all)
        self.text_results_all.setEnabled(False)
        self.text_results_all.setMouseTracking(True)
        self.text_results_all.setAcceptDrops(False)
        self.text_results_all.setObjectName(_fromUtf8("text_results_all"))
        self.verticalLayout_5.addWidget(self.text_results_all)
        self.tabWidget.addTab(self.tab_all, _fromUtf8(""))
        self.tab_anime_index = QtGui.QWidget()
        self.tab_anime_index.setMouseTracking(True)
        self.tab_anime_index.setObjectName(_fromUtf8("tab_anime_index"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tab_anime_index)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setMargin(0)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.text_results_anime_index = QtGui.QTextBrowser(self.tab_anime_index)
        self.text_results_anime_index.setMouseTracking(True)
        self.text_results_anime_index.setAcceptDrops(False)
        self.text_results_anime_index.setObjectName(_fromUtf8("text_results_anime_index"))
        self.verticalLayout_6.addWidget(self.text_results_anime_index)
        self.tabWidget.addTab(self.tab_anime_index, _fromUtf8(""))
        self.tab_anime_tosho = QtGui.QWidget()
        self.tab_anime_tosho.setMouseTracking(True)
        self.tab_anime_tosho.setObjectName(_fromUtf8("tab_anime_tosho"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_anime_tosho)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.text_results_anime_tosho = QtGui.QTextBrowser(self.tab_anime_tosho)
        self.text_results_anime_tosho.setMouseTracking(True)
        self.text_results_anime_tosho.setAcceptDrops(False)
        self.text_results_anime_tosho.setObjectName(_fromUtf8("text_results_anime_tosho"))
        self.verticalLayout_7.addWidget(self.text_results_anime_tosho)
        self.tabWidget.addTab(self.tab_anime_tosho, _fromUtf8(""))
        self.tab_anirena = QtGui.QWidget()
        self.tab_anirena.setMouseTracking(True)
        self.tab_anirena.setObjectName(_fromUtf8("tab_anirena"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.tab_anirena)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.text_results_anirena = QtGui.QTextBrowser(self.tab_anirena)
        self.text_results_anirena.setMouseTracking(True)
        self.text_results_anirena.setAcceptDrops(False)
        self.text_results_anirena.setObjectName(_fromUtf8("text_results_anirena"))
        self.verticalLayout_8.addWidget(self.text_results_anirena)
        self.tabWidget.addTab(self.tab_anirena, _fromUtf8(""))
        self.tab_nyaa = QtGui.QWidget()
        self.tab_nyaa.setMouseTracking(True)
        self.tab_nyaa.setObjectName(_fromUtf8("tab_nyaa"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.tab_nyaa)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.text_results_nyaa = QtGui.QTextBrowser(self.tab_nyaa)
        self.text_results_nyaa.setMouseTracking(True)
        self.text_results_nyaa.setAcceptDrops(False)
        self.text_results_nyaa.setObjectName(_fromUtf8("text_results_nyaa"))
        self.verticalLayout_9.addWidget(self.text_results_nyaa)
        self.tabWidget.addTab(self.tab_nyaa, _fromUtf8(""))
        self.tab_tokyotosho = QtGui.QWidget()
        self.tab_tokyotosho.setMouseTracking(True)
        self.tab_tokyotosho.setObjectName(_fromUtf8("tab_tokyotosho"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_tokyotosho)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setMargin(0)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.text_results_tokyotosho = QtGui.QTextBrowser(self.tab_tokyotosho)
        self.text_results_tokyotosho.setMouseTracking(True)
        self.text_results_tokyotosho.setAcceptDrops(False)
        self.text_results_tokyotosho.setObjectName(_fromUtf8("text_results_tokyotosho"))
        self.verticalLayout_10.addWidget(self.text_results_tokyotosho)
        self.tabWidget.addTab(self.tab_tokyotosho, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 2)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Anime", None))
        self.groupbox_anime_folder.setTitle(_translate("Dialog", "Anime download folder (uTorrent only)", None))
        self.radio_use_default_anime_folder.setText(_translate("Dialog", "Default", None))
        self.text_anime_folder.setPlaceholderText(_translate("Dialog", "Select another folder", None))
        self.button_anime_folder.setText(_translate("Dialog", "...", None))
        self.groupbox_search.setTitle(_translate("Dialog", "Anime", None))
        self.label_name.setText(_translate("Dialog", "Name:", None))
        self.label_search.setText(_translate("Dialog", "Search:", None))
        self.label_episode.setText(_translate("Dialog", "Episode:", None))
        self.checkbox_anime_index.setText(_translate("Dialog", "Anime-Index", None))
        self.checkbox_anime_tosho.setText(_translate("Dialog", "Anime Tosho", None))
        self.checkbox_anirena.setText(_translate("Dialog", "AniRena", None))
        self.checkbox_nyaa.setText(_translate("Dialog", "Nyaa", None))
        self.checkbox_tokyotosho.setText(_translate("Dialog", "Tokyo Toshokan", None))
        self.button_search.setText(_translate("Dialog", "Search", None))
        self.groupbox_information.setTitle(_translate("Dialog", "Information", None))
        self.label_information.setText(_translate("Dialog", "<html><head/><body><p>The name shown in the main screen.</p><p>Type the anime name and click [Search].</p><p>Afterwards, you can customize the search terms to better filter the results.</p></body></html>", None))
        self.button_add.setText(_translate("Dialog", "Add anime", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_all), _translate("Dialog", "All results", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_anime_index), _translate("Dialog", "Anime-Index", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_anime_tosho), _translate("Dialog", "Anime Tosho", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_anirena), _translate("Dialog", "AniRena", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_nyaa), _translate("Dialog", "Nyaa", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_tokyotosho), _translate("Dialog", "Tokyo Toshokan", None))

import qt_resources_rc
